all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_host: 127.0.0.1
      ip: 127.0.0.1
      access_ip: 127.0.0.1
  children:
    kube_control_plane:
      hosts:
        localhost:
    kube_node:
      hosts:
        localhost:
    etcd:
      hosts:
        localhost:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
